const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const customers=[
{id:'KH10001',name:'林晓',case:'72954',phones:[{n:'13800001001',src:['注册手机号','收货手机号']},{n:'18600001001',src:['目前使用手机号']},{n:'15900001001',src:['收货手机号']}]},
{id:'KH10002',name:'陈沐',case:'72977',phones:[{n:'13900001002',src:['注册手机号']},{n:'18700001002',src:['目前使用手机号']},{n:'15800001002',src:['收货手机号']}]},
{id:'KH10003',name:'周宁',case:'74256',phones:[{n:'13700001003',src:['注册手机号']},{n:'18500001003',src:['目前使用手机号']},{n:'15700001003',src:['收货手机号']}]},
{id:'KH10004',name:'许言',case:'74574',phones:[{n:'13600001004',src:['注册手机号']},{n:'15600001004',src:['收货手机号']}]},
{id:'KH10005',name:'顾清',case:'75852',phones:[{n:'13500001005',src:['注册手机号']},{n:'18300001005',src:['目前使用手机号']},{n:'15500001005',src:['收货手机号']}]},
{id:'KH10006',name:'宋禾',case:'77175',phones:[{n:'13400001006',src:['注册手机号','目前使用手机号','收货手机号']}]}];
const mask=n=>n?n.slice(0,3)+'****'+n.slice(-4):'—', customer=id=>customers.find(c=>c.id===id), typeName=t=>t==='sms'?'短信黑名单':'外呼黑名单';
function casePhones(c){const phones=new Map();for(const p of c.phones){if(!p.n)continue;const existing=phones.get(p.n);if(existing)existing.src=[...new Set([...existing.src,...p.src])];else phones.set(p.n,{n:p.n,src:[...p.src]})}return [...phones.values()]}
const registeredPhone=c=>casePhones(c).find(p=>p.src.includes('注册手机号'));
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'});
let records=[
{id:1,cid:'KH10001',type:'sms',dim:'phone',phone:'13800001001',reason:'客户申请暂停该号码短信联系',source:'黑名单维护',by:'孟宪迎',time:'2026-09-10 09:36:12',active:true},
{id:2,cid:'KH10002',type:'sms',dim:'phone',phone:'15800001002',reason:'收货手机号无需短信联系',source:'案件详情',by:'孟宪迎',time:'2026-09-10 09:25:30',active:true},
{id:3,cid:'KH10003',type:'sms',dim:'phone',phone:'18500001003',reason:'目前使用手机号暂停短信联系',source:'案件列表',by:'陈静',time:'2026-09-10 09:18:06',active:true},
{id:4,cid:'KH10004',type:'sms',dim:'phone',phone:'13600001004',reason:'',source:'历史入口',by:'陈静',time:'2026-09-09 16:20:03',active:true},
{id:5,cid:'KH10005',type:'sms',dim:'phone',phone:'13500001005',reason:'客户申请暂停该号码短信联系',source:'黑名单维护',by:'孟宪迎',time:'2026-09-09 15:42:18',active:true},
{id:6,cid:'KH10006',type:'sms',dim:'phone',phone:'13400001006',reason:'客户要求暂停短信',source:'案件列表',by:'陈静',time:'2026-09-09 14:11:00',active:false,removed:'2026-09-10 08:30:00',removeReason:'客户同意恢复联系'},
{id:7,cid:'KH10001',type:'call',dim:'phone',phone:'13800001001',reason:'客户要求仅人工联系',source:'黑名单维护',by:'孟宪迎',time:'2026-09-10 09:36:12',active:true},
{id:8,cid:'KH10003',type:'call',dim:'phone',phone:'13700001003',reason:'客户停止自动外呼',source:'案件列表',by:'陈静',time:'2026-09-10 09:18:06',active:true}];
const key='collection-blacklist-prototype-phone-v2';try{const cached=JSON.parse(localStorage.getItem(key));if(Array.isArray(cached)&&cached.length)records=cached}catch{}
records=records.map(r=>({...r,isComplaint:r.isComplaint===true,dim:'phone'}));
let page='blacklist',tab='sms',pageNo=1,pageSize=10,detailCustomer='KH10001',filters={name:'',phone:'',status:'active',cid:''},formSource='黑名单维护';
const overdueCustomers=new Set();
const isOverdue=r=>r.orderOverdue===true||overdueCustomers.has(r.cid);
const isExpired=r=>r.expiryDate && r.expiryDate < today();
const isInvalid=r=>isOverdue(r)||isExpired(r);
const save=()=>{try{localStorage.setItem(key,JSON.stringify(records))}catch{}};
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',2600)}
function go(p){page=p;render()}
function render(){document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#crumb').textContent=page==='blacklist'?'黑名单维护':page==='cases'?'案件列表':'催收详情';document.title='租后系统 · '+$('#crumb').textContent;if(page==='blacklist')renderList();else if(page==='cases'){renderCases();document.querySelector('.page-heading p')?.remove();document.querySelector('.content > .panel .notice')?.remove()}else renderCustomer()}
const options=(pairs,value)=>pairs.map(([v,l])=>`<option value="${v}" ${value===v?'selected':''}>${l}</option>`).join('');
function heading(title,sub,extra=''){return `<div class="page-heading"><div><h1>${title}</h1><p>${sub}</p></div>${extra}</div>`}
function recordStatus(r){return !r.active?'removed':isInvalid(r)?'expired':'active'}
function statusText(r){return {active:'生效中',expired:'已失效',removed:'已移除'}[recordStatus(r)]}
function effective(r){return recordStatus(r)==='active'}
function listRows(){return records.filter(r=>{const c=customer(r.cid);return r.type===tab&&(!filters.name||c.name.includes(filters.name))&&(!filters.cid||c.id.toLowerCase().includes(filters.cid.toLowerCase()))&&(!filters.status||filters.status===recordStatus(r))&&(!filters.phone||r.phone.includes(filters.phone))})}
function scope(r){return mask(r.phone)}
function sources(r){return r.type==='call'?'注册手机号':casePhones(customer(r.cid)).find(p=>p.n===r.phone)?.src.join(' / ')||'原限制手机号'}
function renderList(){const found=listRows();pageNo=Math.min(pageNo,Math.max(1,Math.ceil(found.length/pageSize)));const shown=found.slice((pageNo-1)*pageSize,pageNo*pageSize);$('#content').innerHTML=heading('黑名单维护','统一维护手机号的短信、自动外呼限制')+`<section class="panel"><form id="query-form" class="filters"><div class="filter"><label for="f-name">客户姓名：</label><input id="f-name" placeholder="请输入客户姓名" value="${esc(filters.name)}"></div><div class="filter"><label for="f-cid">客户编号：</label><input id="f-cid" placeholder="请输入客户编号" value="${esc(filters.cid)}"></div><div class="filter"><label for="f-phone">手机号：</label><input id="f-phone" placeholder="请输入手机号" value="${esc(filters.phone)}"></div><div class="filter"><label for="f-status">名单状态：</label><select id="f-status">${options([['active','生效中'],['removed','已移除'],['expired','已失效'],['','全部']],filters.status)}</select></div><div class="filter-actions"><button class="btn primary" type="submit">查询</button><button class="btn" type="button" id="reset">重置</button></div></form></section><section class="panel"><div class="tabs"><button data-type="sms" class="${tab==='sms'?'active':''}">短信黑名单 <span class="count">${records.filter(r=>r.type==='sms'&&effective(r)).length}</span></button><button data-type="call" class="${tab==='call'?'active':''}">外呼黑名单 <span class="count">${records.filter(r=>r.type==='call'&&effective(r)).length}</span></button></div><div class="notice"><span class="info-icon">i</span><span>${tab==='sms'?'短信黑名单同时限制自动、手工发送，仅限制所选手机号。':'外呼黑名单仅限制注册手机号的自动外呼，人工仍可拨打。'}</span></div><div class="toolbar"><span class="muted" style="font-size:12px">添加黑名单请从案件列表发起</span><span class="muted" style="font-size:12px">共 ${found.length} 条记录</span></div><div class="table-wrap"><table><thead><tr><th>客户信息</th><th>限制手机号</th><th>加入原因</th><th>加入人 / 时间</th><th>有效期截止日</th><th>状态</th><th>操作</th></tr></thead><tbody>${shown.map(r=>`<tr><td><button class="link" data-customer="${r.cid}">${customer(r.cid).name}</button><small>${r.cid}</small></td><td>${scope(r)}<small>${sources(r)}</small></td><td title="${esc(r.reason)}">${esc(r.reason.length>14?r.reason.slice(0,14)+'…':r.reason)}</td><td>${esc(r.by)}<small>${r.time}</small></td><td>${r.expiryDate||'长期有效'}<small>${isOverdue(r)?'订单已转逾期':''}</small></td><td><span class="status ${effective(r)?'':'off'}">${statusText(r)}</span></td><td><button class="link" data-view="${r.id}">详情</button>${r.active?`<button class="link red" data-remove="${r.id}">移除</button>`:''}</td></tr>`).join('')||'<tr><td colspan="7" class="empty"><div class="empty-icon">▤</div>暂无符合条件的黑名单记录</td></tr>'}</tbody></table></div><div class="pagination">共 ${found.length} 条<select id="page-size" aria-label="每页条数">${options([['5','5条/页'],['10','10条/页'],['20','20条/页']],String(pageSize))}</select><button id="prev" aria-label="上一页" ${pageNo===1?'disabled':''}>‹</button><button class="active">${pageNo}</button><button id="next" aria-label="下一页" ${pageNo*pageSize>=found.length?'disabled':''}>›</button></div></section>`;
$('#query-form').onsubmit=e=>{e.preventDefault();filters={name:$('#f-name').value.trim(),cid:$('#f-cid').value.trim(),phone:$('#f-phone').value.trim(),status:$('#f-status').value};pageNo=1;renderList()};$('#reset').onclick=()=>{filters={name:'',phone:'',status:'active',cid:''};pageNo=1;renderList()};document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{tab=b.dataset.type;pageNo=1;renderList()});$('#page-size').onchange=e=>{pageSize=+e.target.value;pageNo=1;renderList()};$('#prev').onclick=()=>{pageNo--;renderList()};$('#next').onclick=()=>{pageNo++;renderList()};bindRecordActions()}
function bindRecordActions(){document.querySelectorAll('[data-customer]').forEach(b=>b.onclick=()=>{detailCustomer=b.dataset.customer;go('detail')});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>viewRecord(+b.dataset.view));document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeRecord(+b.dataset.remove))}
let focusBefore;
function modal(title,body,foot){focusBefore=document.activeElement;$('#modal-title').textContent=title;$('#modal-body').innerHTML=body;$('#modal-foot').innerHTML=foot;$('#overlay').hidden=false;$('.close').focus();$('.close').onclick=closeModal;$('#cancel')?.addEventListener('click',closeModal)}
function closeModal(){$('#overlay').hidden=true;focusBefore?.focus()}
function openAdd(cid,prephone='',source='案件列表'){
if(page!=='cases'||!customer(cid))return;formSource='案件列表';const c=customer(cid),reg=registeredPhone(c);
modal('加入黑名单',`<dl class="detail-grid"><dt>客户</dt><dd>${c.name}　<span class="muted">${c.id}</span><input id="add-customer" type="hidden" value="${cid}"></dd></dl>
<div class="formrow"><div class="formlabel"><span class="req">*</span>黑名单类型</div><div><div class="radio-line"><label><input type="checkbox" name="type" value="sms" ${tab==='sms'?'checked':''}>短信黑名单</label><label><input type="checkbox" name="type" value="call" ${tab==='call'?'checked':''}>外呼黑名单</label></div><div class="helper">可同时选择；短信按所选手机号限制，外呼固定限制注册手机号。</div></div></div>
<div class="formrow"><div class="formlabel"><span class="req">*</span>是否投诉</div><div><div class="radio-line"><label><input type="radio" name="complaint" value="yes">是</label><label><input type="radio" name="complaint" value="no" checked>否</label></div></div></div>
<section id="sms-config" class="blacklist-config"><h3>短信黑名单设置</h3><div class="formrow"><div class="formlabel"><span class="req">*</span>短信手机号</div><div><div class="phone-options">${casePhones(c).map(p=>`<label class="phone-option"><input type="checkbox" name="phone" value="${p.n}" ${p.n===prephone?'checked':''}><b style="font-weight:400">${mask(p.n)}</b><span>${p.src.join(' / ')}</span></label>`).join('')}</div><div class="helper">自动加载当前案件手机号，可多选；仅限制所选号码的自动、手工短信。</div></div></div></section>
<section id="call-config" class="blacklist-config"><h3>外呼黑名单设置</h3><div class="formrow"><div class="formlabel">外呼手机号</div><div><input aria-label="外呼注册手机号" value="${mask(reg?.n)}" readonly><div class="helper">${reg?'注册手机号 · 仅禁止自动外呼，人工仍可拨打。':'当前案件暂无注册手机号，无法加入外呼黑名单。'}</div></div></div></section>
<div class="formrow"><label class="formlabel" for="expiry-date"><span class="req">*</span>有效期截止日</label><div><div class="radio-line"><label><input type="radio" name="expiry-mode" value="date" checked>指定日期</label><label><input type="radio" name="expiry-mode" value="forever">长期有效</label></div><input id="expiry-date" type="date" min="${today()}"><div class="helper">截止日当日有效，次日00:00自动失效；订单从未逾期转为逾期时也会自动失效。</div></div></div><div class="formrow" style="margin-bottom:0"><label class="formlabel" for="reason"><span class="req">*</span>加入原因</label><div><textarea id="reason" maxlength="200" placeholder="请填写加入黑名单的原因，最多200字"></textarea><div class="helper" style="text-align:right"><span id="reason-count">0</span> / 200</div><div id="form-error" class="error" role="alert"></div></div></div>`,`<button class="btn" id="cancel">取消</button><button class="btn primary" id="confirm-add">确认加入</button>`);
function preview(){$('#sms-config').hidden=!$('input[name=type][value=sms]').checked;$('#call-config').hidden=!$('input[name=type][value=call]').checked}
document.querySelectorAll('input[name=type],input[name=phone],input[name=expiry-mode]').forEach(x=>x.onchange=()=>{if(x.name==='expiry-mode')$('#expiry-date').disabled=x.value==='forever';preview()});$('#reason').oninput=e=>$('#reason-count').textContent=e.target.value.length;$('#confirm-add').onclick=submitAdd;preview();}
function submitAdd(){const cid=$('#add-customer').value,types=[...document.querySelectorAll('input[name=type]:checked')].map(x=>x.value),smsPhones=[...document.querySelectorAll('input[name=phone]:checked')].map(x=>x.value),isComplaint=$('input[name=complaint]:checked')?.value==='yes',reason=$('#reason').value.trim(),c=customer(cid),reg=c?registeredPhone(c):undefined;const err=!c?'请选择客户':!types.length?'请至少选择一种黑名单类型':!$('input[name=complaint]:checked')?'请选择是否投诉':types.includes('sms')&&!smsPhones.length?'请至少选择一个短信手机号':types.includes('call')&&!reg?'当前案件暂无注册手机号，无法加入外呼黑名单':types.includes('sms')&&smsPhones.some(n=>!casePhones(c).some(p=>p.n===n))?'请从当前案件手机号中选择':!reason?'请填写加入原因':$('input[name=expiry-mode]:checked')?.value==='date'&&!$('#expiry-date')?.value?'请选择有效期截止日':$('input[name=expiry-mode]:checked')?.value==='date'&&$('#expiry-date').value<today()?'有效期截止日不能早于今天':'';if(err){$('#form-error').textContent=err;return}const pairs=[];if(types.includes('sms'))smsPhones.forEach(phone=>pairs.push({type:'sms',dim:'phone',phone}));if(types.includes('call'))pairs.push({type:'call',dim:'phone',phone:reg.n});const fresh=pairs.filter(p=>!records.some(r=>effective(r)&&r.cid===cid&&r.type===p.type&&r.phone===p.phone));if(!fresh.length){$('#form-error').textContent='所选对象已在对应黑名单中，无需重复加入。';return}let id=Math.max(...records.map(r=>r.id))+1;const now=new Date().toLocaleString('sv-SE'),expiryDate=$('input[name=expiry-mode]:checked')?.value==='forever'?'':$('#expiry-date').value;fresh.forEach(p=>records.unshift({id:id++,cid,...p,isComplaint,reason,source:formSource,by:'孟宪迎',time:now,expiryDate,active:true}));save();closeModal();render();if(page==='cases')manageCustomerBlacklist(cid);toast(`已加入 ${fresh.length} 条黑名单${pairs.length>fresh.length?'，重复记录已跳过':''}`)}
function effect(r){if(!effective(r))return '本条记录已不再限制该号码；是否可联系以其他生效记录为准。';return `${mask(r.phone)}${r.type==='sms'?'禁止自动、手工发送短信。':'禁止自动外呼，人工仍可拨打。'}`}
function removeRecord(id,onBack){const r=records.find(r=>r.id===id);modal('移除黑名单',`<div class="notice"><span class="info-icon">i</span><span>确认移除 ${customer(r.cid).name} 的${typeName(r.type)}记录？</span></div><dl class="detail-grid" style="margin-top:22px"><dt>客户</dt><dd>${customer(r.cid).name}　<span class="muted">${r.cid}</span></dd><dt>黑名单类型</dt><dd>${typeName(r.type)}</dd><dt>限制手机号</dt><dd>${mask(r.phone)}<div class="helper">${sources(r)}</div></dd><dt>是否投诉</dt><dd>${r.isComplaint===true?'是':'否'}</dd><dt>加入原因</dt><dd>${esc(r.reason)}</dd><dt>有效期截止日</dt><dd>${r.expiryDate||'长期有效'}${isOverdue(r)?'（订单已转逾期，自动失效）':''}</dd><dt>加入人 / 时间</dt><dd>${esc(r.by)}　${r.time}</dd><dt>名单状态</dt><dd><span class="status ${effective(r)?'':'off'}">${statusText(r)}</span></dd></dl><div class="scope-box">${effect(r)}</div>`,`<button class="btn" id="cancel">取消</button><button class="btn danger" id="confirm-remove">确认移除</button>`);if(onBack)$('#cancel').onclick=onBack;$('#confirm-remove').onclick=()=>{r.active=false;r.removed=new Date().toLocaleString('sv-SE');r.removedBy='孟宪迎';save();closeModal();render();if(onBack)onBack();toast('已移除黑名单')}}
function viewRecord(id){const r=records.find(x=>x.id===id);modal('黑名单详情',`<dl class="detail-grid"><dt>客户</dt><dd>${customer(r.cid).name}　<span class="muted">${r.cid}</span></dd><dt>黑名单类型</dt><dd>${typeName(r.type)}</dd><dt>限制手机号</dt><dd>${mask(r.phone)}<div class="helper">${sources(r)}</div></dd><dt>是否投诉</dt><dd>${r.isComplaint===true?'是':'否'}</dd><dt>加入原因</dt><dd>${esc(r.reason)}</dd><dt>有效期截止日</dt><dd>${r.expiryDate||'长期有效'}${isOverdue(r)?'（订单已转逾期，自动失效）':''}</dd><dt>加入人 / 时间</dt><dd>${esc(r.by)}　${r.time}</dd><dt>名单状态</dt><dd><span class="status ${effective(r)?'':'off'}">${statusText(r)}</span></dd></dl><div class="scope-box">${effect(r)}</div>`,`<button class="btn" id="cancel">关闭</button>${r.active?'<button class="btn" id="detail-remove">移除黑名单</button>':''}`);$('#detail-remove')?.addEventListener('click',()=>removeRecord(id))}
function manageCustomerBlacklist(cid){const c=customer(cid),active=records.filter(r=>r.cid===cid&&r.active);modal('黑名单管理',`<div class="toolbar" style="margin-top:0"><div><b>${c.name}</b><div class="helper">共 ${active.filter(effective).length} 条生效记录</div></div><button class="btn primary" id="manager-add">＋ 加入黑名单</button></div><div class="phone-options">${active.map(r=>`<div style="padding:16px;border-bottom:1px solid #ebeef5"><div style="display:flex;justify-content:space-between;gap:12px"><div><b style="font-weight:500">${typeName(r.type)}</b></div><div style="white-space:nowrap"><button class="link" data-manager-edit="${r.id}">编辑</button><button class="link red" data-manager-remove="${r.id}">移除</button></div></div><div style="margin-top:8px">${mask(r.phone)}　<span class="status ${effective(r)?'':'off'}">${statusText(r)}</span></div><div class="helper">${sources(r)}</div><div class="helper">是否投诉：${r.isComplaint===true?'是':'否'}</div><div class="helper">有效期截止日：${r.expiryDate||'长期有效'}</div><div class="helper">加入原因：${esc(r.reason)}</div></div>`).join('')||'<div class="empty" style="height:auto;padding:40px">该客户暂无生效黑名单，可点击“加入黑名单”。</div>'}</div>`,`<button class="btn" id="cancel">关闭</button>`);$('#manager-add').onclick=()=>{openAdd(cid);$('#cancel').onclick=()=>manageCustomerBlacklist(cid)};document.querySelectorAll('[data-manager-edit]').forEach(b=>b.onclick=()=>editBlacklist(+b.dataset.managerEdit));document.querySelectorAll('[data-manager-remove]').forEach(b=>b.onclick=()=>removeRecord(+b.dataset.managerRemove,()=>manageCustomerBlacklist(cid)))}
function editBlacklist(id){
const r=records.find(x=>x.id===id),c=customer(r.cid),reg=registeredPhone(c),phones=casePhones(c);
if(!phones.some(p=>p.n===r.phone))phones.push({n:r.phone,src:['原限制手机号']});
modal('编辑黑名单',`<dl class="detail-grid"><dt>客户</dt><dd>${c.name}</dd></dl>
<div class="formrow"><label class="formlabel" for="edit-type">黑名单类型</label><select id="edit-type">${options([['sms','短信黑名单'],['call','外呼黑名单']],r.type)}</select></div>
<div class="formrow"><div class="formlabel"><span class="req">*</span>是否投诉</div><div class="radio-line"><label><input type="radio" name="edit-complaint" value="yes" ${r.isComplaint===true?'checked':''}>是</label><label><input type="radio" name="edit-complaint" value="no" ${r.isComplaint===true?'':'checked'}>否</label></div></div>
<div class="formrow" id="edit-sms-row"><label class="formlabel" for="edit-phone"><span class="req">*</span>短信手机号</label><select id="edit-phone">${phones.map(p=>`<option value="${p.n}" ${p.n===r.phone?'selected':''}>${mask(p.n)}　${p.src.join(' / ')}</option>`).join('')}</select></div>
<div class="formrow" id="edit-call-row"><label class="formlabel" for="edit-call-phone">外呼手机号</label><div><input id="edit-call-phone" readonly value="${mask(reg?.n)}"><div class="helper">${reg?'注册手机号 · 仅禁止自动外呼，人工仍可拨打。':'当前案件暂无注册手机号，无法保存外呼黑名单。'}</div></div></div>
<div class="formrow"><label class="formlabel" for="edit-expiry-date"><span class="req">*</span>有效期截止日</label><div><div class="radio-line"><label><input type="radio" name="edit-expiry-mode" value="date" ${r.expiryDate?'checked':''}>指定日期</label><label><input type="radio" name="edit-expiry-mode" value="forever" ${r.expiryDate?'':'checked'}>长期有效</label></div><input id="edit-expiry-date" type="date" min="${today()}" value="${r.expiryDate||''}"><div class="helper">截止日当日有效，次日00:00自动失效；订单从未逾期转为逾期时也会自动失效。</div></div></div>
<div class="formrow"><label class="formlabel" for="edit-reason"><span class="req">*</span>加入原因</label><textarea id="edit-reason" maxlength="200">${esc(r.reason)}</textarea></div><div class="error" id="edit-error" role="alert"></div>`,`<button class="btn" id="cancel">取消</button><button class="btn primary" id="save-edit">保存修改</button>`);
$('#cancel').onclick=()=>manageCustomerBlacklist(r.cid);
function preview(){const call=$('#edit-type').value==='call';$('#edit-sms-row').style.display=call?'none':'grid';$('#edit-call-row').style.display=call?'grid':'none';$('#edit-expiry-date').disabled=$('input[name=edit-expiry-mode]:checked').value==='forever'}
$('#edit-type').onchange=preview;document.querySelectorAll('input[name=edit-expiry-mode]').forEach(x=>x.onchange=preview);preview();
$('#save-edit').onclick=()=>{
const type=$('#edit-type').value,phone=type==='call'?reg?.n:$('#edit-phone').value,reason=$('#edit-reason').value.trim(),complaint=$('input[name=edit-complaint]:checked'),expiryDate=$('input[name=edit-expiry-mode]:checked').value==='forever'?'':$('#edit-expiry-date').value;
let err=!phone?'请选择有效的手机号':!complaint?'请选择是否投诉':!reason?'请填写加入原因':!$('#edit-expiry-date').disabled&&!expiryDate?'请选择有效期截止日':expiryDate&&expiryDate<today()?'有效期截止日不能早于今天':'';
if(!err&&records.some(x=>x.id!==id&&effective(x)&&x.cid===r.cid&&x.type===type&&x.phone===phone))err='已存在相同类型和手机号的生效记录，请直接编辑该记录。';
if(err){$('#edit-error').textContent=err;return}
Object.assign(r,{type,dim:'phone',phone,isComplaint:complaint.value==='yes',reason,expiryDate});save();closeModal();render();manageCustomerBlacklist(r.cid);toast('黑名单已更新');
};
}
function blocked(cid,type,phone){return records.some(r=>effective(r)&&r.cid===cid&&r.type===type&&r.phone===phone)}
function renderCases(){$('#content').innerHTML=heading('案件列表','通过“黑名单管理”统一处理当前客户的加入、编辑和移除')+`<section class="panel"><div class="notice"><span class="info-icon">i</span>仅从案件列表添加黑名单，客户由当前案件自动带入；可选择黑名单类型；短信自动带入当前案件手机号，外呼自动带入注册手机号。</div><div class="toolbar"><div class="tabs" style="margin:0;border:0"><button class="active">全部</button><button disabled>提醒</button><button disabled>M1-A</button><button disabled>M1-B</button><button disabled>M2</button><button disabled>M3</button></div><button class="btn" id="manage">黑名单维护</button></div><div class="table-wrap"><table><thead><tr><th>案件编号</th><th>客户姓名</th><th>注册手机号</th><th>催收员</th><th>短信限制</th><th>自动外呼</th><th>操作</th></tr></thead><tbody>${customers.map(c=>`<tr><td><button class="link" data-customer="${c.id}">${c.case}</button></td><td>${c.name}</td><td>${mask(registeredPhone(c)?.n)}</td><td>陈静</td><td>${records.some(r=>r.cid===c.id&&r.type==='sms'&&effective(r))?'<span class="tag">存在黑名单</span>':'—'}</td><td>${blocked(c.id,'call',registeredPhone(c)?.n)?'<span class="tag gray">已限制</span>':'未被黑名单限制'}</td><td><button class="link" data-customer="${c.id}">详情</button><button class="link" data-case-manage="${c.id}">黑名单管理</button></td></tr>`).join('')}</tbody></table></div><div class="pagination">共 ${customers.length} 条　<span>10条/页</span><button class="active">1</button></div></section>`;$('#manage').onclick=()=>go('blacklist');bindRecordActions();document.querySelectorAll('[data-case-manage]').forEach(b=>b.onclick=()=>manageCustomerBlacklist(b.dataset.caseManage))}
function renderCustomer(){const c=customer(detailCustomer);$('#content').innerHTML=`<section class="panel"><div class="case-tabs"><b>作业详情</b><span>订单详情</span><span>催收记录</span><span>短信记录</span><span>客服工单</span></div><div class="card-header"><h2>客户信息</h2></div><div class="section-title">基本信息</div><div class="customer-summary"><div><h2>${c.name} <span class="muted" style="font-size:13px">${c.id}</span></h2><p>企微客服（信审）　—</p><p>个微/企微（贷后）　—</p></div><div>${c.phones.filter(p=>p.src.some(s=>s!=='收货手机号')).map(p=>`<div class="phone-row"><span>${p.src.includes('注册手机号')?'注册手机号':'目前使用手机号'}</span><span>${mask(p.n)}</span></div>`).join('')}${!c.phones.some(p=>p.src.includes('目前使用手机号'))?'<div class="phone-row"><span>目前使用手机号</span><span>—</span></div>':''}</div></div><h2 class="section-divider">收货地址</h2><div class="table-wrap" style="margin-top:15px"><table><thead><tr><th>收货人</th><th>收货电话</th><th>收货地址</th></tr></thead><tbody>${c.phones.filter(p=>p.src.includes('收货手机号')).map(p=>`<tr><td>${c.name}</td><td>${mask(p.n)}</td><td>演示地址</td></tr>`).join('')}</tbody></table></div></section>`}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));document.addEventListener('keydown',e=>{if($('#overlay').hidden)return;if(e.key==='Escape')closeModal();if(e.key==='Tab'){const f=[...$('.modal').querySelectorAll('button,input,select,textarea')].filter(x=>!x.disabled&&x.offsetParent!==null),first=f[0],last=f.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});render();
